services:
  - type: web
    name: classification-local-website
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true

databases:
  - name: fabricguard-db
    plan: free
    region: oregon
    databaseName: fabricguard
    user: fabricguard_user
